import { Injectable } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';

export interface DashboardStats {
  totalBales: number;
  totalWeight: number;
  mixPlans: number;
  completedPlans: number;
  pendingPlans: number;
  averageQuality: number;
  monthlyGrowth: number;
}

export interface RecentActivity {
  id: string;
  type: 'bale_added' | 'mix_created' | 'quality_check' | 'plan_completed';
  title: string;
  description: string;
  timestamp: Date;
  icon: string;
}

export interface QuickAction {
  id: string;
  title: string;
  description: string;
  icon: string;
  route: string;
  color: string;
}

export interface ChartData {
  labels: string[];
  datasets: {
    label: string;
    data: number[];
    backgroundColor?: string | string[];
    borderColor?: string | string[];
    borderWidth?: number;
    fill?: boolean;
    tension?: number;
  }[];
}

@Injectable({
  providedIn: 'root'
})
export class DashboardService {
  private statsSubject = new BehaviorSubject<DashboardStats>({
    totalBales: 1247,
    totalWeight: 2847,
    mixPlans: 23,
    completedPlans: 18,
    pendingPlans: 5,
    averageQuality: 8.5,
    monthlyGrowth: 12
  });

  private activitiesSubject = new BehaviorSubject<RecentActivity[]>([
    {
      id: '1',
      type: 'bale_added',
      title: 'New Bale Added',
      description: 'Grade A Cotton bale added to inventory',
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
      icon: '📦'
    },
    {
      id: '2',
      type: 'mix_created',
      title: 'AI Mix Plan Created',
      description: 'New cotton mix plan generated by AI',
      timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
      icon: '🤖'
    },
    {
      id: '3',
      type: 'quality_check',
      title: 'Quality Check Passed',
      description: 'Batch #1234 passed quality inspection',
      timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
      icon: '✅'
    },
    {
      id: '4',
      type: 'plan_completed',
      title: 'Mix Plan Completed',
      description: 'Production plan #567 completed successfully',
      timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
      icon: '🎯'
    },
    {
      id: '5',
      type: 'bale_added',
      title: 'Inventory Updated',
      description: '5 new bales added to warehouse',
      timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000),
      icon: '📦'
    }
  ]);

  private quickActionsSubject = new BehaviorSubject<QuickAction[]>([
    {
      id: '1',
      title: 'Add New Bale',
      description: 'Add a new cotton bale to inventory',
      icon: '📦',
      route: '/bale-inventory',
      color: '#3498db'
    },
    {
      id: '2',
      title: 'Create Mix Plan',
      description: 'Generate AI-powered cotton mix plan',
      icon: '🤖',
      route: '/ai-mix-planner',
      color: '#9b59b6'
    },
    {
      id: '3',
      title: 'View Reports',
      description: 'Access detailed analytics and reports',
      icon: '📊',
      route: '/reports',
      color: '#e74c3c'
    },
    {
      id: '4',
      title: 'Quality Check',
      description: 'Perform quality inspection',
      icon: '🔍',
      route: '/quality-check',
      color: '#f39c12'
    }
  ]);

  constructor() {
    this.startStatsUpdates();
  }

  getStats(): Observable<DashboardStats> {
    return this.statsSubject.asObservable();
  }

  getActivities(): Observable<RecentActivity[]> {
    return this.activitiesSubject.asObservable();
  }

  getQuickActions(): Observable<QuickAction[]> {
    return this.quickActionsSubject.asObservable();
  }

  // Chart data methods
  getDailySalesData(): ChartData {
    return {
      labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul'],
      datasets: [{
        label: 'Daily Sales',
        data: [65, 59, 80, 81, 56, 55, 40],
        backgroundColor: 'rgba(46, 204, 113, 0.2)',
        borderColor: 'rgba(46, 204, 113, 1)',
        borderWidth: 2,
        fill: true,
        tension: 0.4
      }]
    };
  }

  getGlobalReferralsData(): ChartData {
    return {
      labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul'],
      datasets: [{
        label: 'Global Referrals',
        data: [12, 19, 3, 5, 2, 3, 7],
        backgroundColor: [
          'rgba(243, 156, 18, 0.8)',
          'rgba(243, 156, 18, 0.8)',
          'rgba(243, 156, 18, 0.8)',
          'rgba(243, 156, 18, 0.8)',
          'rgba(243, 156, 18, 0.8)',
          'rgba(243, 156, 18, 0.8)',
          'rgba(243, 156, 18, 0.8)'
        ],
        borderColor: 'rgba(243, 156, 18, 1)',
        borderWidth: 1
      }]
    };
  }

  getCompletedTasksData(): ChartData {
    return {
      labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul'],
      datasets: [{
        label: 'Completed Tasks',
        data: [28, 48, 40, 19, 86, 27, 90],
        backgroundColor: 'rgba(231, 76, 60, 0.2)',
        borderColor: 'rgba(231, 76, 60, 1)',
        borderWidth: 2,
        fill: true,
        tension: 0.4
      }]
    };
  }

  getQualityTrendData(): ChartData {
    return {
      labels: ['Week 1', 'Week 2', 'Week 3', 'Week 4'],
      datasets: [{
        label: 'Quality Score',
        data: [8.2, 8.5, 8.8, 8.9],
        backgroundColor: 'rgba(52, 152, 219, 0.2)',
        borderColor: 'rgba(52, 152, 219, 1)',
        borderWidth: 3,
        fill: false,
        tension: 0.1
      }]
    };
  }

  getProductionEfficiencyData(): ChartData {
    return {
      labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      datasets: [{
        label: 'Production Efficiency',
        data: [85, 88, 92, 87, 90, 95, 89],
        backgroundColor: 'rgba(155, 89, 182, 0.2)',
        borderColor: 'rgba(155, 89, 182, 1)',
        borderWidth: 2,
        fill: true,
        tension: 0.3
      }]
    };
  }

  getInventoryLevelsData(): ChartData {
    return {
      labels: ['Grade A', 'Grade B', 'Grade C', 'Mixed'],
      datasets: [{
        label: 'Inventory Levels',
        data: [45, 30, 15, 10],
        backgroundColor: [
          'rgba(46, 204, 113, 0.8)',
          'rgba(52, 152, 219, 0.8)',
          'rgba(243, 156, 18, 0.8)',
          'rgba(231, 76, 60, 0.8)'
        ],
        borderColor: [
          'rgba(46, 204, 113, 1)',
          'rgba(52, 152, 219, 1)',
          'rgba(243, 156, 18, 1)',
          'rgba(231, 76, 60, 1)'
        ],
        borderWidth: 1
      }]
    };
  }

  private startStatsUpdates() {
    setInterval(() => {
      const currentStats = this.statsSubject.value;
      const updatedStats = {
        ...currentStats,
        totalBales: currentStats.totalBales + Math.floor(Math.random() * 3),
        totalWeight: currentStats.totalWeight + Math.floor(Math.random() * 50),
        monthlyGrowth: currentStats.monthlyGrowth + (Math.random() > 0.5 ? 1 : -1)
      };
      this.statsSubject.next(updatedStats);
    }, 30000);
  }

  addActivity(activity: Omit<RecentActivity, 'id' | 'timestamp'>) {
    const newActivity: RecentActivity = {
      ...activity,
      id: Date.now().toString(),
      timestamp: new Date()
    };
    
    const currentActivities = this.activitiesSubject.value;
    const updatedActivities = [newActivity, ...currentActivities.slice(0, 4)];
    this.activitiesSubject.next(updatedActivities);
  }

  updateStats(newStats: Partial<DashboardStats>) {
    const currentStats = this.statsSubject.value;
    this.statsSubject.next({ ...currentStats, ...newStats });
  }
}
